export const prompts: Record<string, string> = {
  quebecois: "Generate a Quebecois slang-based lorem ipsum style text full of humorous and creative.",
  canadian: "Generate a Canadian slang-based lorem ipsum style text full of humorous and creative.",
  romanian: "Generate a Romanian slang-based lorem ipsum style text full of humorous and creative.",
  popCulture90s: "Generate a lorem ipsum-style text as if written by a 90s sitcom character.",
  superhero: "Create funny lorem ipsum inspired by superhero catchphrases and dialogues.",
  pirate: "Write a lorem ipsum based on a pirate's vocabulary.",
  medievalBlacksmith: "Generate text using phrases a quirky medieval blacksmith might say.",
  techSupport: "Create a lorem ipsum as if written by a sarcastic tech support agent.",
  officeGossip: "Write funny office gossip lorem ipsum from an overenthusiastic coworker.",
  australian: "Create funny Australian slang-based lorem ipsum.",
  southernBBQ: "Generate lorem ipsum in Southern U.S. barbecue pitmaster style.",
  britishTea: "Write lorem ipsum with British tea-drinking clichés.",
  catMonologue: "Generate lorem ipsum from a cat's sarcastic inner monologue.",
  dogNarration: "Write funny lorem ipsum as if a dog is narrating their day.",
  parrotOverhearing: "Create lorem ipsum inspired by a parrot overhearing weird conversations.",
  victorianWriter: "Write lorem ipsum in the style of a Victorian-era writer with quirky expressions.",
  timeTraveler: "Generate lorem ipsum text as if it's written by a time traveler from the year 3000.",
  romanGraffiti: "Create a lorem ipsum based on ancient Roman graffiti.",
  breakupTexts: "Generate lorem ipsum with over-the-top breakup texts.",
  productReviews: "Write lorem ipsum in the style of exaggerated online product reviews.",
  motivationalQuotes: "Create lorem ipsum inspired by cringe-worthy motivational quotes.",
  millennialStruggles: "Write lorem ipsum text using 'millennial struggles' memes as inspiration.",
  genZSlang: "Generate lorem ipsum with Gen Z slang and TikTok trends.",
  viralMeme: "Create lorem ipsum as if every sentence ends with a viral meme phrase.",
  fantasyBard: "Generate lorem ipsum as if it were written by a bard in a fantasy tavern.",
  sarcasticWizard: "Write lorem ipsum using phrases a sarcastic wizard might use in spells.",
  goblinTreasures: "Create funny lorem ipsum inspired by a goblin selling secondhand treasures.",
  pizzaLover: "Write lorem ipsum in the voice of a passionate pizza lover.",
  weirdFood: "Generate funny lorem ipsum inspired by weird food combinations.",
  foodCritics: "Create a lorem ipsum using phrases from overdramatic food critics.",
  amateurGolfer: "Generate lorem ipsum as if written by a grumpy amateur golfer.",
  gamerCommentary: "Write funny lorem ipsum inspired by a competitive gamer’s commentary.",
  gymTrainer: "Create lorem ipsum based on funny gym trainer motivational slogans.",
  scottishRant: "Generate a lorem ipsum inspired by a fiery Scotsman ranting in a pub.",
  scottishPhrases: "Write a lorem ipsum filled with quirky Scottish phrases and Highland slang.",
  scottishGranny: "Create lorem ipsum as if a Scottish granny is gossiping about the neighbors.",
  poshBritish: "Generate lorem ipsum using over-the-top posh British slang.",
  cheekyBrit: "Write lorem ipsum inspired by a cheeky Brit having tea and biscuits.",
  sarcasticLondoner: "Create funny lorem ipsum using phrases a sarcastic Londoner might say.",
  aussieBBQ: "Generate a lorem ipsum text based on Aussie slang from a beachside barbecue.",
  outbackAdventurer: "Write funny lorem ipsum inspired by an outback adventurer’s diary.",
  aussieSlang: "Create a lorem ipsum using phrases like 'fair dinkum' and 'crikey!' in every sentence.",
};